name: meally2
description: personalized meal planning and ordering service

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.9.7+2
  image: ^2.0.7
  animator: 0.1.4
  image_picker: ^0.6.0+2
  google_sign_in: ^4.0.1+1
  timeago: 2.0.17
  cached_network_image:
  firebase_auth: ^0.8.3
  geolocator: 5.0.1
  uuid: ^2.0.0
  firebase_core: 0.3.1+1
  cupertino_icons: ^0.1.2
  path_provider: ^1.4.0
  firebase_messaging: ^4.0.0+1
  firebase_storage: ^2.1.0+1
  hexcolor: ^1.0.4
  bubble_bottom_bar: ^1.2.0
  google_fonts: ^1.1.0
  sk_onboarding_screen: ^1.0.1
  animated_walkthrough: ^0.0.1+1
  smooth_star_rating: ^1.1.1
  flutter_native_image: ^0.0.5+3
  date_time_picker_widget: ^0.1.0
  day_night_time_picker: ^0.4.0
  dropdown_date_picker: ^0.1.1+2
  http: ^0.12.0+2
  flutter_swiper: ^1.1.6
  tab_indicator_styler: ^1.0.0
  salomon_bottom_bar: ^2.0.0
  date_picker_timeline: ^1.2.1
  maps_launcher: ^1.2.2+2
  flutter_svg:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/homepage.jpg
    - assets/images/eating.png
    - assets/images/eatCrop.png
    - assets/images/background.png
    - assets/images/train.png
    - assets/images/Schedule.png
    - assets/images/google.png
    - assets/images/rest.png
    - assets/images/restaurant.jpg
    - assets/images/healthy.png
    - assets/images/bg.png
    - assets/images/diet.png
    - assets/images/restBg.jpg
    - assets/images/cooking.gif
    - assets/images/card.png
    - assets/images/loadOr.gif
    - assets/images/thinking.gif
    - assets/images/pay.gif
    - assets/images/plan1.png
    - assets/images/plan2.png
    - assets/images/plan3.png
    - assets/images/hello.png
    - assets/images/Chef.png
    - assets/images/upload1.png
    - assets/images/upload2.png
    - assets/images/upload3.png
    - assets/images/upload4.png
    - assets/images/upload5.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
